//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using RobotRuntime.Graphics;
        ///using System.Collections.Generic;
        ///using System.Drawing;
        ///
        ///namespace CustomNamespace
        ///{
        ///    public class BigImageDetectorFake : FeatureDetector
        ///    {
        ///        public override string Name { get { return &quot;FakeDetector&quot;; } }
        ///        public override bool SupportsMultipleMatches { get { return true; } }
        ///
        ///        public override IEnumerable&lt;Point[]&gt; FindImageMultiplePos(Bitmap smallBmp, Bitmap bigBmp)
        ///        {
        ///            yield return smallBmp.Width &gt;= 10 ? MakeARect(new Poi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BigImageDetectorFake {
            get {
                return ResourceManager.GetString("BigImageDetectorFake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using RobotRuntime;
        ///using RobotRuntime.Tests;
        ///
        ///namespace CustomNamespace
        ///{
        ///    [Serializable]
        ///    public class CommandLog : Command
        ///    {
        ///        public override string Name =&gt; &quot;CommandLog&quot;;
        ///        public override bool CanBeNested =&gt; false;
        ///
        ///        public int Number;
        ///
        ///        public CommandLog() { }
        ///
        ///        public override void Run(TestData TestData)
        ///        {
        ///            Logger.Log(LogType.Log, &quot;CommandLog: &quot; + Number);
        ///        }
        ///
        ///        public CommandLog(int number)        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommandLog {
            get {
                return ResourceManager.GetString("CommandLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace CustomNamespace
        ///{
        ///    // This script purpose is for tests only. code inside the main method references a class in a precompilied user
        ///    // dll which is copied into a project by test. Look for &quot;PluginTests&quot;
        ///    public class SomeClassUsingUserPlugin
        ///    {
        ///        public static int main()
        ///        {
        ///            return TestClassLibrary.Class.Method();
        ///        }
        ///    }
        ///} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SomeClassUsingUserPlugin {
            get {
                return ResourceManager.GetString("SomeClassUsingUserPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TestClassLibrary {
            get {
                object obj = ResourceManager.GetObject("TestClassLibrary", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TestClassLibraryWithRefToRobot {
            get {
                object obj = ResourceManager.GetObject("TestClassLibraryWithRefToRobot", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
